In [1]:
import pandas as pd
import numpy as np

In [2]:
rain = pd.read_csv("https://raw.githubusercontent.com/fedhere/DSPS/master/labs/1865331.csv")

In [3]:
# rain["DATE"] ## getting only values from one coulmns 
# rain["DATE"].values ## convert them in to array

rainonly = rain[["DATE", "PRCP"]]

In [4]:
rainonly

            DATE  PRCP
0     2010-01-01  0.28
1     2010-01-02  0.00
2     2010-01-03  0.00
3     2010-01-04  0.00
4     2010-01-05  0.00
5     2010-01-06  0.00
6     2010-01-07  0.00
7     2010-01-08  0.05
8     2010-01-09  0.00
9     2010-01-10  0.00
10    2010-01-11  0.00
11    2010-01-12  0.00
12    2010-01-13  0.00
13    2010-01-14  0.00
14    2010-01-15  0.00
15    2010-01-16  0.00
16    2010-01-17  0.00
17    2010-01-18  0.74
18    2010-01-19  0.00
19    2010-01-20  0.00
20    2010-01-21  0.00
21    2010-01-22  0.00
22    2010-01-23  0.00
23    2010-01-24  0.00
24    2010-01-25  0.38
25    2010-01-26  1.42
26    2010-01-27  0.00
27    2010-01-28  0.00
28    2010-01-29  0.00
29    2010-01-30  0.00
...          ...   ...
3508  2019-08-10  0.00
3509  2019-08-11  0.00
3510  2019-08-12  0.00
3511  2019-08-13  0.00
3512  2019-08-14  0.05
3513  2019-08-15  0.94
3514  2019-08-16  0.00
3515  2019-08-17  0.00
3516  2019-08-18  0.00
3517  2019-08-19  0.04
3518  2019-08-20  0.00
3519  2019-08-21  0.07
3520  2019-08-22  0.00
3521  2019-08-23  0.26
3522  2019-08-24  0.21
3523  2019-08-25  0.00
3524  2019-08-26  0.00
3525  2019-08-27  0.00
3526  2019-08-28  0.00
3527  2019-08-29  0.01
3528  2019-08-30  0.00
3529  2019-08-31  0.00
3530  2019-09-01  0.00
3531  2019-09-02  0.00
3532  2019-09-03  0.00
3533  2019-09-04  0.00
3534  2019-09-05  0.00
3535  2019-09-06  0.00
3536  2019-09-07  0.02
3537  2019-09-08  0.00

[3538 rows x 2 columns]

In [5]:
# rainonly.DATE.dtype ## checking the data type in the onject

rainonly['date'] = pd.to_datetime(rainonly.DATE) ## converting into readable format

/home/narayan/miniconda3/lib/python3.7/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until

In [6]:
# rainonly['date'] > pd.to_datetime("2018/01/01")

recent = rainonly[rainonly['date'] > pd.to_datetime("2018/01/01")] ## picking a sample from the population

In [7]:
# maean and std of sample
mean_sample = (recent['PRCP'].values).mean()
std_sample = (recent['PRCP'].values).std()

In [8]:
# mean and std of population
mean_pop = 0.137
std_pop = 0.38
N = len(recent) ## length of sample

In [10]:
# applying Z-test
Z = (mean_sample -mean_pop)/(std_pop/np.sqrt(N))
print(Z)

1.664421697050835

In [ ]:
#As the test statistics is less than 2, we cannot reject null hypothesis